#!/usr/bin/env bash

SET_STAGE=$(cat /sdcard/.setup)

set -e

# White
msg() {
    echo -e "$@"
}

# Yellow
info() {
    printf "\033[1;33m$@\033[0m\n"
}

# Green
success() {
    printf "\033[0;32m$@\033[0m\n"
}

# Red
fail() {
    printf "\033[0;31m$@\033[0m\n"
    exit 1
}

add_to_file() {
    grep -qF -- "$1" "$2" || echo "$1" >> "$2"
}

if [ "$SET_STAGE" -eq "4" ]
then
    # GIT CLONE FLOWPILOT
    cd ~/ && [ ! -d 'flowpilot' ] && git clone https://github.com/flowdriveai/flowpilot.git -b master || true
    cd ~/flowpilot && git submodule update --init
    # INSTALL DEPS
    ./get_dependencies.sh
    sleep 5
    scons
    echo "5" > /sdcard/.setup
    SET_STAGE=5
fi

# when it's all said and done, launch FlowPilot's env
if [ "$SET_STAGE" -eq "5" ]
then
    cd ~/flowpilot
    ./launch_flowpilot.sh
    # let android know the env is running so flowpilot can be launched
    touch /tmp/chroot_booted
fi

success "Flowpilot successfully installed. launch using cd flowpilot && ./launch_flowpilot.sh"