#!/usr/bin/env bash

if ! command -v tmux &> /dev/null
then
  sudo apt-get update
  sudo apt-get install tmux
  sudo apt install -y openssh-server

  # setup perms for ssh and set password
  echo "Port 8022" >> /etc/ssh/sshd_config
  echo "PermitRootLogin yes" >> /etc/ssh/sshd_config
  echo "root:retros" | chpasswd

fi

/usr/sbin/sshd -D &

tmux new-session -d -s retropilot /usr/bin/bash flowpilot_userland